[build]
  command = "npm run generate"
  publish = ".output/public"

# SPA fallback (Nuxt static)
[[redirects]]
  from = "/*"
  to   = "/200.html"
  status = 200

# ─────────────────────────────────────────────────────────────
# Caching

# Nuxt build assets (cache-busted filenames)
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Nuxt Image / IPX generated variants
[[headers]]
  for = "/_ipx/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Public image folders (put your site images under /images/*)
[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Root icons / social images
[[headers]]
  for = "/favicon.png"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/og-image.jpg"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Recent projects gallery (if you serve images from /recent/*)
[[headers]]
  for = "/recent/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# HTML should revalidate quickly
[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

# ─────────────────────────────────────────────────────────────
# Security headers

[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Canonical redirect for Netlify subdomain → custom domain
# [[redirects]]
#   from = "/*"
#   to   = "https://REPLACE_YOUR_DOMAIN/:splat"
#   status = 301
#   conditions = { Host = ["your-site.netlify.app"] }

# Canonical redirect for Netlify subdomain → custom domain
# [[redirects]]
#   from = "/*"
#   to   = "https://REPLACE_YOUR_DOMAIN/:splat"
#   status = 301
#   conditions = { Host = ["your-site.netlify.app"] }

# Canonical redirect for Netlify subdomain → custom domain
# [[redirects]]
#   from = "/*"
#   to   = "https://REPLACE_YOUR_DOMAIN/:splat"
#   status = 301
#   conditions = { Host = ["your-site.netlify.app"] }

# Canonical redirect for Netlify subdomain → custom domain
# [[redirects]]
#   from = "/*"
#   to   = "https://REPLACE_YOUR_DOMAIN/:splat"
#   status = 301
#   conditions = { Host = ["your-site.netlify.app"] }

# Canonical redirect for Netlify subdomain → custom domain
# [[redirects]]
#   from = "/*"
#   to   = "https://REPLACE_YOUR_DOMAIN/:splat"
#   status = 301
#   conditions = { Host = ["your-site.netlify.app"] }
